Trying to add fontawesome icons in safari
aweandreverence/www.aweandreverence.com pull request #12
Opened 2021-01-15 04:44 UTC by eang0521

2021-02-03 04:23 UTC, eang0521 commented
![Screen Shot 2021-02-02 at 8 22 09 PM](https://user-images.githubusercontent.com/57340860/106697813-693b6f00-6594-11eb-9a50-49b889c36628.png)

Moved the facebook and twitter icons to the top of the copyright. Currently does not work in Safari.

2021-02-03 06:56 UTC, jontsai requested changes

2021-02-03 06:56 UTC, jontsai commented on components/footer.js
> +            <link
While we're using FontAwesome here in the footer, the `<link>` tag is supposed to belong in the `<head>` section of an HTML document, semantically.

You're going to want to move this tag to the HTML the correct file in the head section, which I believe is here: https://github.com/aweandreverence/www.aweandreverence.com/blob/fcba8f5178e1ce7891a0e140fb06f55e165532ff/components/base_page.js#L25

2021-02-05 04:25 UTC, jontsai approved these changes
LGTM

2021-02-05 04:26 UTC, merged